### ISSUE TITLE
An attempt at some organization

### ISSUE THREAD

**Issue by matthewdias** [beardedspice/beardedspice#378]
This is just me trying to organize my thoughts about things that need to be worked on here before I start contributing. There's a lot here, so I decided to just put it all in one place, rather than clutter the repo with more issues. Please comment with any thoughts you have, and if you think any are good candidates create an issue and assign yourself if you'd like to. Maybe this could become a 2.0 milestone proposal?

## maintainance
- prs 

not much to say here

- [ ] issues

remove dead issues and tag others with `app support` or `enhancement` etc.

## performance
- [ ] control lag

theres a good second of lag between pressing a mediakey, and the website responding

- [ ] ui lag

haven't looked through how the ui is updated yet, but changes in things like the currently playing track take awhile to update, and don't happen until you open the menu

## play logic
- [ ] switch when another starts playing

when a player starts playing (isPlaying), should automatically become the active player

- [ ] stop when switching
- [ ] notification on player switch

when the player switches, any other players should be paused, and the user should be notified

- [ ] notification on track change #144

notification behavior is weird right now. this could be solved by the suggestions for better strategies below (event track change)

## player support
There have been some requests to control players other than websites in chrome/safari, and native apps that implement `ScriptingBridge`. This would require additional ways for beardedspice to be able to recognize and control players.

- [ ] mpd #221

can be controlled via mpc shell commands, maybe http (not sure on this one)

- [ ] chromecast

would be cool to be able to control a chromecast on the local network. if we could knock out this and mpd support with an http strategy that would be awesome

- [ ] electron, chrome, nwjs, fluid #285, #23, #324

wrappers of webapps. adding applescript support had been discussed, but probably requires more work than it is worth. Another option would be to port chrome's scripting bridge to electron and nwjs, since they are chromium based, but this is scary and probably way out of the scope of this project. 

here's my proposal:

create a _javascript shim_ that can be easily included in external projects that sends data between the webapp and beardedspice via something like websocket. simplify does something similar [here](https://github.com/mmth/simplify_web_suite_core)

## better strategies

As brought up in #302, i'm in favor of all js strategies for the long term (though the sooner, the better, as they enable many more advanced features below, and it will be less of a pain to rewrite them)

I also think that the app could benefit greatly from more detailed strategies, and many of the features I suggest here depend on them. I realise it will be a lot of work to update the existing strategies, but I think it would be for the better.

- [ ] properties

a js object that contains booleans for the optional features it supports (more details below), as well as an icon

- [ ] get artist (required)

separate out track title and artist name

- [ ] get length (time) #332 (optional because of livestreams)

get the length of the track so we can determine playhead position

- [ ] get volume (optional)
- [ ] set volume (optional)

not sure if this is useful. i personally just leave in app volume controls all the way up, and let the system volume handle it.

- [ ] set time #332 (optional)
- [ ] seek in increments (optional)

useful for long media like podcasts and movies

- [ ] set thumbs up (optional)
- [ ] set thumbs down (optional)

replaces favorite

- [ ] event play
- [ ] event pause
- [ ] event stop/close
- [ ] event track change

beardedspice is notified instantly of these changes, so it can react immediately with out looking for the change in isPlaying. this should help with ui lag and performance, as we dont have to poll for isPlaying

## new control methods
- [ ] today view widget

ideally this would replace the menubar item. includes playback controls, album art, seek bar, player icon, preferences shortcut, and (maybe) volume slider

- [ ] notification action #342
    

- clicking on the notification opens the active player/tab
- for track change notifications, there is a skip action

- [ ] cli #332
- [ ] applescript #332

for external scripting/development

## other features
- [ ] last.fm scrobbling

**Comment by Coder-256** [comment]
+1!!! I _completely_ agree and I have always hoped that some of these features would be added over time. I would just like to point out that many of these goals are very ambitious and will take lots of time to implement. They definitely should be added and tested one by one in a separate branch, if they are even used at all.

I would also like to suggest migrating to Swift, unless too many of the developers are unfamiliar with it (@Stillness-2, do you know Swift?).

**Comment by matthewdias** [comment]
Swift would be awesome too. I'm definitely more comfortable in it than Obj-c, but it might be tricky, as many of the low level libraries haven't been ported yet. Maybe we could do a gradual shift. Yeah, much of this is really ambitious, but I've been following this project for awhile, and though a lot of great work has been put in, not a lot has changed functionality-wise. Thought it would be a good idea just to lay out all my ideas, so we have a central place to refer to possible future plans.

**Comment by Stillness-2** [comment]
Your ideas to God's ears. Well, to be honest, don't expect someone else to fulfill your ideas. Just do it yourself. It will be a good proof of Your potency. Anyway, enough of wasting words. It's opensource. You can advance the development of the project, but with chores, not chatter.

A good example of the right approach is #302 (@1ps0).

@Coder-256, how's it going with #332? Are you going to, or have already "thrown shit on the fan"? :)

Excuse my abrupt writing style :)

**Comment by matthewdias** [comment]
@Stillness-2 yup, I plan to, just getting it all down

**Comment by Coder-256** [comment]
@Stillness-2 I'm better at Swift (which is why I suggested porting), and I only have basic Objective-C skills (not enough to do such a huge thing as implementing an external API). However, I will try to do it in Swift if you are OK with that.

@matthewdias Objective-C libraries can be used in Swift, just not vice versa.

I would also like to suggest updating CocoaPods to the 1.0 beta. Here are the steps:

```Shell
gem install --pre cocoapods
pod install
```

**Comment by Stillness-2** [comment]
@matthewdias "so no one does any unnecessary work that doesn't end up getting merged."

This is a complete nonsense :) If these changes are important to you, then you write them yourself, regardless of will this contribution be merged or not. You just try to do what you think is important and see if it works and is good enough to be merged. But if these changes are not that important to you then what makes you think that someone else will need it?

**Comment by Stillness-2** [comment]
@Coder-256 
First of all, please explain to me. Why does BS need to be rewritten in Swift? What is the purpose???
Secondly, to justify the increase in the number of programming languages in the project we totally need to have a good reason. You must understand that it will affect the software maintenance badly. So what do you think IS a good reason???

**Comment by Coder-256** [comment]
@Stillness-2 There are many reasons why Swift is better. [InfoWorld wrote a two-page article about some of them](http://www.infoworld.com/article/2920333/mobile-development/swift-vs-objective-c-10-reasons-the-future-favors-swift.html). However, you do bring up a good point that it would be best to have as few languages as possible, so I will avoid using Swift (unless you want to do a rewrite, which I understand is a big undertaking).

**Comment by 1ps0** [comment]
@Coder-256 
Swift will be a good language, and already is since that article was written (May of 2015, almost a full year ago). However, it still has many major strides to take before it's worth evaluating for converting a project like this.

If this was a new project it might be good to investigate building in Swift from the ground up. But converting it will take much more effort, pain, and time than anyone is willing to invest. The payoff is simply not worth it. 

However, as @Stillness-2 said above, you should be the change you want to see in the app. If it's valuable to you, then do it. Make sure you test thoroughly :)
